target_sources(Math
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/BoolVector2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BoolVector2.hpp
    ${CMAKE_CURRENT_LIST_DIR}/BoolVector3.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BoolVector3.hpp
    ${CMAKE_CURRENT_LIST_DIR}/BoolVector4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BoolVector4.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ByteColor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ColorDefinitions.hpp
    ${CMAKE_CURRENT_LIST_DIR}/EulerAngles.cpp
    ${CMAKE_CURRENT_LIST_DIR}/EulerAngles.hpp
    ${CMAKE_CURRENT_LIST_DIR}/EulerOrder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/EulerOrder.hpp
    ${CMAKE_CURRENT_LIST_DIR}/IntVector2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/IntVector2.hpp
    ${CMAKE_CURRENT_LIST_DIR}/IntVector3.cpp
    ${CMAKE_CURRENT_LIST_DIR}/IntVector3.hpp
    ${CMAKE_CURRENT_LIST_DIR}/IntVector4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/IntVector4.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Math.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Math.hpp
    ${CMAKE_CURRENT_LIST_DIR}/MathImports.hpp
    ${CMAKE_CURRENT_LIST_DIR}/MathTypedefs.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Matrix2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Matrix2.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Matrix3.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Matrix3.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Matrix4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Matrix4.hpp
    ${CMAKE_CURRENT_LIST_DIR}/MatrixStorage.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Quaternion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Quaternion.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Reals.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Reals.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SharedVectorFunctions.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Vector2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Vector2.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Vector3.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Vector3.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Vector3.inl
    ${CMAKE_CURRENT_LIST_DIR}/Vector4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Vector4.hpp
)
