target_sources(Foundation
  PRIVATE
     ${CMAKE_CURRENT_LIST_DIR}/BitField.hpp
     ${CMAKE_CURRENT_LIST_DIR}/Determinism.cpp
     ${CMAKE_CURRENT_LIST_DIR}/Determinism.hpp
     ${CMAKE_CURRENT_LIST_DIR}/Diagnostic.cpp
     ${CMAKE_CURRENT_LIST_DIR}/Diagnostic.hpp
     ${CMAKE_CURRENT_LIST_DIR}/EnumDeclaration.hpp
     ${CMAKE_CURRENT_LIST_DIR}/Precompiled.cpp
     ${CMAKE_CURRENT_LIST_DIR}/Precompiled.hpp
     ${CMAKE_CURRENT_LIST_DIR}/Standard.hpp
     ${CMAKE_CURRENT_LIST_DIR}/StringFormat.hpp
     ${CMAKE_CURRENT_LIST_DIR}/Typedefs.hpp
)
